# Generated automatically from Makefile.in by configure.
ALL:helloworld
helloworld:task2 task3 task4

task1:
	mpicc -o task2 task2.c

task2:
	mpicc -o task3 Task3.c

task4:
	mpicc -o task4 Task4.c
clean:
	/bin/rm -f task *.o

    
